[build-system]
requires = ["setuptools", "wheel"]  # PEP 508 specifications.

[tool.black]
line-length = 79
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.vscode
    | \.mypy_cache
    | \env
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''